<?php

// main FWD Simple 3D Coverflow Data class
class FWDS3DCovData
{
	// constants
	const DEFAULT_SKINS_NR = 18;
	
	// variables
	public $settings_ar;
    public $playlists_ar;
	
	private $_dir_url;
	
    // constructor
    public function FWDS3DCovData()
    {
		$this->_dir_url = plugin_dir_url(dirname(__FILE__));
	
		$cur_data = get_option("fwds3dcov_data");
	       
	    if (!$cur_data)
	    {
	    	$this->init_settings();
	    	$this->set_data();
	    }
    	
    	$this->set_updates();
    	
    	$this->get_data();
    }
	
	private function reset_presets()
	{
		$this->get_data();
		$this->init_settings();
	    $this->set_data();
	}
	
	private function set_updates()
	{
		$this->get_data();
		
   		foreach ($this->settings_ar as &$preset)
    	{
			// update new or existing fields
	    	if (!array_key_exists("infinite_loop", $preset))
	    	{
	    		$preset["infinite_loop"] = "no";
			}
			
			if (!array_key_exists("right_click_context_menu", $preset))
			{
				unset($preset["show_context_menu"]);
				$preset["right_click_context_menu"] = "developer";
			}
			
			if (!array_key_exists("fluid_width_z_index", $preset))
	    	{
	    		$preset["fluid_width_z_index"] = 1000;
			}
			
			// update plugin dir url
			$pattern = "/\/[^\/]*\/load\/skin/";
			$parts = explode("/", trim($this->_dir_url, "/"));
			$preset["skin_path"] = preg_replace($pattern, "/" . $parts[count($parts)-1] . "/load/skin", $preset["skin_path"]);
    	}
		
		$this->set_data();
	}
    
    // functions
    private function init_settings()
    {
    	$this->settings_ar = array(
									array(
											// main settings
											"id" => 0,
											"name" => "skin_black_preset1",
											"display_type" => "fluidwidth",
											"autoscale" => "yes",
											"cov_width" => 940,
											"cov_height" => 538,
											"skin_path" => $this->_dir_url . "load/skin_black",
											"cov_bg_color" => "#000000",
											"cov_bg_image_url" => "",
											"bg_repeat" => "repeat-x",
											"show_2d_display" => "no",
											"cov_start_pos" => "center",
											"cov_topology" => "dualsided",
											"cov_x_rot" => 0,
											"cov_y_rot" => 0,
											"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
											"cov_autoplay" => "no",
											"cov_slideshow_delay" => 5000,
											"right_click_context_menu" => "developer",
											"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
											
											// thumbs settings
											"thumb_width" => 400,
											"thumb_height" => 266,
											"thumb_x_offset_3d" => 86,
											"thumb_x_space_3d" => 78,
											"thumb_z_offset_3d" => 200,
											"thumb_z_space_3d" => 93,
											"thumb_y_angle_3d" => 70,
											"thumb_x_offset_2d" => 20,
											"thumb_x_space_2d" => 30,
											"thumb_hover_offset" => 100,
											"thumb_border_size" => 0,
											"thumb_bg_color" => "#FFFFFF",
											"thumb_border_color1" => "#FFFFFF",
											"thumb_border_color2" => "#FFFFFF",
											"transparent_images" => "no",
											"thumbs_alignment" => "center",
											"max_thumbs_mobile" => 13,
											"show_thumbs_gradient" => "yes",
											"thumb_gradient_color1" => "rgba(0, 0, 0, 0)",
											"thumb_gradient_color2" => "rgba(0, 0, 0, 1)",
											"show_thumbs_text" => "yes",
											"text_offset" => 10,
											"show_thumb_box_shadow" => "yes",
											"box_shadow_css" => "0px 2px 2px #111111",
											"show_tooltip" => "no",
											"dynamic_tooltip" => "yes",
											"show_reflection" => "yes",
											"reflection_height" => 60,
											"reflection_distance" => 0,
											"reflection_opacity" => .4,
											
											// controls settings
											"controls_max_width" => 700,
											"controls_position" => "bottom",
											"controls_offset" => 15,
											"show_prev_btn" => "yes",
											"show_next_btn" => "yes",
											"disable_btns_mobile" => "no",
											"show_slideshow_btn" => "yes",
											"timer_color" => "#FFFFFF",
											"show_scrollbar" => "yes",
											"scrollbar_handler_width" => 200,
											"scrollbar_text_normal_color" => "#000000",
											"scrollbar_text_selected_color" => "#FFFFFF",
											"disable_scrollbar_mobile" => "yes",
											"enable_mouse_wheel" => "yes",
											
											// categories menu settings
											"show_categories_menu" => "yes",
											"start_category" => 1,
											"categories_menu_max_width" => 700,
											"categories_menu_offset" => 25,
											"category_normal_color" => "#999999",
											"category_selected_color" => "#FFFFFF",
											
											// lightbox settings
											"lightbox_keyboard_support" => "yes",
											"show_lightbox_next_prev_btns" => "yes",
											"show_lightbox_zoom_btn" => "yes",
											"show_lightbox_info_btn" => "yes",
											"show_lightbox_slideshow_btn" => "yes",
											"show_lightbox_info_default" => "no",
											"lightbox_slideshow_autoplay" => "no",
											"lightbox_video_autoplay" => "no",
											"lightbox_video_width" => 640,
											"lightbox_video_height" => 480,
											"lightbox_iframe_width" => 800,
											"lightbox_iframe_height" => 600,
											"lightbox_bg_color" => "#000000",
											"lightbox_info_bg_color" => "#FFFFFF",
											"lightbox_item_border_color1" => "#FCFDFD",
											"lightbox_item_border_color2" => "#E4E4E4",
											"lightbox_item_bg_color" => "#333333",
											"lightbox_bg_opacity" => .8,
											"lightbox_info_bg_opacity" => .9,
											"lightbox_border_size" => 0,
											"lightbox_border_radius" => 0,
											"lightbox_slideshow_delay" => 4000
									),
					    			array(
					    					// main settings
					    					"id" => 1,
					    					"name" => "skin_black_preset2",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_black",
					    					"cov_bg_color" => "#000000",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "dualsided",
					    					"cov_x_rot" => 0,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
					    					"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    						
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 80,
					    					"thumb_x_space_3d" => 165,
					    					"thumb_z_offset_3d" => 400,
					    					"thumb_z_space_3d" => 130,
					    					"thumb_y_angle_3d" => -40,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 100,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#FFFFFF",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "no",
					    					"thumb_gradient_color1" => "rgba(0, 0, 0, 0)",
					    					"thumb_gradient_color2" => "rgba(0, 0, 0, 1)",
					    					"show_thumbs_text" => "yes",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #111111",
					    					"show_tooltip" => "no",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .4,
					    						
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    						
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#FFFFFF",
					    						
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 2,
					    					"name" => "skin_black_preset3",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_black",
					    					"cov_bg_color" => "#000000",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "dualsided",
					    					"cov_x_rot" => 0,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
					    					"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    						
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 86,
					    					"thumb_x_space_3d" => 78,
					    					"thumb_z_offset_3d" => 200,
					    					"thumb_z_space_3d" => 93,
					    					"thumb_y_angle_3d" => 2,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 100,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#FFFFFF",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "no",
					    					"thumb_gradient_color1" => "rgba(0, 0, 0, 0)",
					    					"thumb_gradient_color2" => "rgba(0, 0, 0, 1)",
					    					"show_thumbs_text" => "yes",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #111111",
					    					"show_tooltip" => "no",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .4,
					    						
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    						
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#FFFFFF",
					    						
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 3,
					    					"name" => "skin_black_preset4",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_black",
					    					"cov_bg_color" => "#000000",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "dualsided",
					    					"cov_x_rot" => 15,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
					    					"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 100,
					    					"thumb_x_space_3d" => 20,
					    					"thumb_z_offset_3d" => 150,
					    					"thumb_z_space_3d" => 30,
					    					"thumb_y_angle_3d" => 60,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 50,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#FFFFFF",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "yes",
					    					"thumb_gradient_color1" => "rgba(0, 0, 0, .4)",
					    					"thumb_gradient_color2" => "rgba(0, 0, 0, 1)",
					    					"show_thumbs_text" => "yes",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #111111",
					    					"show_tooltip" => "no",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .4,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#FFFFFF",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 4,
					    					"name" => "skin_black_preset5",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_black",
					    					"cov_bg_color" => "#000000",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "onesided",
					    					"cov_x_rot" => 15,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
					    					"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 240,
					    					"thumb_x_space_3d" => 0,
					    					"thumb_z_offset_3d" => 0,
					    					"thumb_z_space_3d" => 20,
					    					"thumb_y_angle_3d" => 0,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 0,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#FFFFFF",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "yes",
					    					"thumb_gradient_color1" => "rgba(0, 0, 0, .2)",
					    					"thumb_gradient_color2" => "rgba(0, 0, 0, 1)",
					    					"show_thumbs_text" => "yes",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #111111",
					    					"show_tooltip" => "no",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .4,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#FFFFFF",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 5,
					    					"name" => "skin_black_preset6",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_black",
					    					"cov_bg_color" => "#000000",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "crosssided",
					    					"cov_x_rot" => 15,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
					    					"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 240,
					    					"thumb_x_space_3d" => 0,
					    					"thumb_z_offset_3d" => 0,
					    					"thumb_z_space_3d" => 20,
					    					"thumb_y_angle_3d" => 0,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 0,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#FFFFFF",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "yes",
					    					"thumb_gradient_color1" => "rgba(0, 0, 0, 1)",
					    					"thumb_gradient_color2" => "rgba(0, 0, 0, .2)",
					    					"show_thumbs_text" => "yes",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #111111",
					    					"show_tooltip" => "no",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .4,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#FFFFFF",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 6,
					    					"name" => "skin_black_preset7",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_black",
					    					"cov_bg_color" => "#000000",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "frontonesided",
					    					"cov_x_rot" => 3,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 100,
					    					"thumb_x_space_3d" => 30,
					    					"thumb_z_offset_3d" => 150,
					    					"thumb_z_space_3d" => 60,
					    					"thumb_y_angle_3d" => 60,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 50,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#FFFFFF",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "yes",
					    					"thumb_gradient_color1" => "rgba(0, 0, 0, 1)",
					    					"thumb_gradient_color2" => "rgba(0, 0, 0, .2)",
					    					"show_thumbs_text" => "yes",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #111111",
					    					"show_tooltip" => "no",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .4,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#FFFFFF",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 7,
					    					"name" => "skin_black_preset8",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_black",
					    					"cov_bg_color" => "#000000",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "accordion",
					    					"cov_x_rot" => 10,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 86,
					    					"thumb_x_space_3d" => 78,
					    					"thumb_z_offset_3d" => 200,
					    					"thumb_z_space_3d" => 93,
					    					"thumb_y_angle_3d" => 70,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 0,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#FFFFFF",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "no",
					    					"thumb_gradient_color1" => "rgba(0, 0, 0, 0)",
					    					"thumb_gradient_color2" => "rgba(0, 0, 0, 1)",
					    					"show_thumbs_text" => "yes",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #111111",
					    					"show_tooltip" => "no",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .4,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#FFFFFF",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 8,
					    					"name" => "skin_black_preset9",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_black",
					    					"cov_bg_color" => "#000000",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "flipping",
					    					"cov_x_rot" => 0,
					    					"cov_y_rot" => 30,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 86,
					    					"thumb_x_space_3d" => 78,
					    					"thumb_z_offset_3d" => 200,
					    					"thumb_z_space_3d" => 93,
					    					"thumb_y_angle_3d" => 70,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 0,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#FFFFFF",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "no",
					    					"thumb_gradient_color1" => "rgba(0, 0, 0, 0)",
					    					"thumb_gradient_color2" => "rgba(0, 0, 0, 1)",
					    					"show_thumbs_text" => "yes",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #111111",
					    					"show_tooltip" => "no",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .4,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#FFFFFF",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
    								array(
											// main settings
											"id" => 9,
											"name" => "skin_white_preset1",
											"display_type" => "fluidwidth",
											"autoscale" => "yes",
											"cov_width" => 940,
											"cov_height" => 538,
											"skin_path" => $this->_dir_url . "load/skin_white",
											"cov_bg_color" => "#FFFFFF",
											"cov_bg_image_url" => "",
											"bg_repeat" => "repeat-x",
											"show_2d_display" => "no",
											"cov_start_pos" => "center",
											"cov_topology" => "dualsided",
											"cov_x_rot" => 0,
											"cov_y_rot" => 0,
											"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
											"cov_autoplay" => "no",
											"cov_slideshow_delay" => 5000,
											"right_click_context_menu" => "developer",
											"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
											
											// thumbs settings
											"thumb_width" => 400,
											"thumb_height" => 266,
											"thumb_x_offset_3d" => 86,
											"thumb_x_space_3d" => 78,
											"thumb_z_offset_3d" => 200,
											"thumb_z_space_3d" => 93,
											"thumb_y_angle_3d" => 70,
											"thumb_x_offset_2d" => 20,
											"thumb_x_space_2d" => 30,
											"thumb_hover_offset" => 100,
											"thumb_border_size" => 0,
											"thumb_bg_color" => "#999999",
											"thumb_border_color1" => "#FFFFFF",
											"thumb_border_color2" => "#FFFFFF",
											"transparent_images" => "no",
											"thumbs_alignment" => "center",
											"max_thumbs_mobile" => 13,
											"show_thumbs_gradient" => "yes",
											"thumb_gradient_color1" => "rgba(255, 255, 255, 0)",
											"thumb_gradient_color2" => "rgba(255, 255, 255, 1)",
											"show_thumbs_text" => "no",
											"text_offset" => 10,
											"show_thumb_box_shadow" => "yes",
											"box_shadow_css" => "0px 2px 2px #BBBBBB",
											"show_tooltip" => "yes",
											"dynamic_tooltip" => "yes",
											"show_reflection" => "yes",
											"reflection_height" => 60,
											"reflection_distance" => 0,
											"reflection_opacity" => .2,
											
											// controls settings
											"controls_max_width" => 700,
											"controls_position" => "bottom",
											"controls_offset" => 15,
											"show_prev_btn" => "yes",
											"show_next_btn" => "yes",
											"disable_btns_mobile" => "no",
											"show_slideshow_btn" => "yes",
											"timer_color" => "#FFFFFF",
											"show_scrollbar" => "yes",
											"scrollbar_handler_width" => 200,
											"scrollbar_text_normal_color" => "#000000",
											"scrollbar_text_selected_color" => "#FFFFFF",
											"disable_scrollbar_mobile" => "yes",
											"enable_mouse_wheel" => "yes",
											
											// categories menu settings
											"show_categories_menu" => "yes",
											"start_category" => 1,
											"categories_menu_max_width" => 700,
											"categories_menu_offset" => 25,
											"category_normal_color" => "#999999",
											"category_selected_color" => "#000000",
											
											// lightbox settings
											"lightbox_keyboard_support" => "yes",
											"show_lightbox_next_prev_btns" => "yes",
											"show_lightbox_zoom_btn" => "yes",
											"show_lightbox_info_btn" => "yes",
											"show_lightbox_slideshow_btn" => "yes",
											"show_lightbox_info_default" => "no",
											"lightbox_slideshow_autoplay" => "no",
											"lightbox_video_autoplay" => "no",
											"lightbox_video_width" => 640,
											"lightbox_video_height" => 480,
											"lightbox_iframe_width" => 800,
											"lightbox_iframe_height" => 600,
											"lightbox_bg_color" => "#000000",
											"lightbox_info_bg_color" => "#FFFFFF",
											"lightbox_item_border_color1" => "#FCFDFD",
											"lightbox_item_border_color2" => "#E4E4E4",
											"lightbox_item_bg_color" => "#333333",
											"lightbox_bg_opacity" => .8,
											"lightbox_info_bg_opacity" => .9,
											"lightbox_border_size" => 0,
											"lightbox_border_radius" => 0,
											"lightbox_slideshow_delay" => 4000
									),
					    			array(
					    					// main settings
					    					"id" => 10,
					    					"name" => "skin_white_preset2",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_white",
					    					"cov_bg_color" => "#FFFFFF",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "dualsided",
					    					"cov_x_rot" => 0,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    						
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 80,
					    					"thumb_x_space_3d" => 165,
					    					"thumb_z_offset_3d" => 400,
					    					"thumb_z_space_3d" => 130,
					    					"thumb_y_angle_3d" => -40,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 100,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#999999",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "no",
					    					"thumb_gradient_color1" => "rgba(255, 255, 255, 0)",
					    					"thumb_gradient_color2" => "rgba(255, 255, 255, 1)",
					    					"show_thumbs_text" => "no",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #BBBBBB",
					    					"show_tooltip" => "yes",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .2,
					    						
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    						
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#000000",
					    						
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 11,
					    					"name" => "skin_white_preset3",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_white",
					    					"cov_bg_color" => "#FFFFFF",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "dualsided",
					    					"cov_x_rot" => 0,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    						
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 86,
					    					"thumb_x_space_3d" => 78,
					    					"thumb_z_offset_3d" => 200,
					    					"thumb_z_space_3d" => 93,
					    					"thumb_y_angle_3d" => 2,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 100,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#999999",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "no",
					    					"thumb_gradient_color1" => "rgba(255, 255, 255, 0)",
					    					"thumb_gradient_color2" => "rgba(255, 255, 255, 1)",
					    					"show_thumbs_text" => "no",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #BBBBBB",
					    					"show_tooltip" => "yes",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .2,
					    						
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    						
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#000000",
					    						
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 12,
					    					"name" => "skin_white_preset4",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_white",
					    					"cov_bg_color" => "#FFFFFF",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "dualsided",
					    					"cov_x_rot" => 15,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 100,
					    					"thumb_x_space_3d" => 20,
					    					"thumb_z_offset_3d" => 150,
					    					"thumb_z_space_3d" => 30,
					    					"thumb_y_angle_3d" => 60,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 50,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#999999",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "yes",
					    					"thumb_gradient_color1" => "rgba(255, 255, 255, .4)",
					    					"thumb_gradient_color2" => "rgba(255, 255, 255, 1)",
					    					"show_thumbs_text" => "no",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #BBBBBB",
					    					"show_tooltip" => "yes",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .2,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#000000",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 13,
					    					"name" => "skin_white_preset5",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_white",
					    					"cov_bg_color" => "#FFFFFF",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "onesided",
					    					"cov_x_rot" => 15,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 240,
					    					"thumb_x_space_3d" => 0,
					    					"thumb_z_offset_3d" => 0,
					    					"thumb_z_space_3d" => 20,
					    					"thumb_y_angle_3d" => 0,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 0,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#999999",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "yes",
					    					"thumb_gradient_color1" => "rgba(255, 255, 255, .2)",
					    					"thumb_gradient_color2" => "rgba(255, 255, 255, 1)",
					    					"show_thumbs_text" => "no",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #BBBBBB",
					    					"show_tooltip" => "yes",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .2,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#000000",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 14,
					    					"name" => "skin_white_preset6",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_white",
					    					"cov_bg_color" => "#FFFFFF",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "crosssided",
					    					"cov_x_rot" => 15,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 240,
					    					"thumb_x_space_3d" => 0,
					    					"thumb_z_offset_3d" => 0,
					    					"thumb_z_space_3d" => 20,
					    					"thumb_y_angle_3d" => 0,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 0,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#999999",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "yes",
					    					"thumb_gradient_color1" => "rgba(255, 255, 255, 1)",
					    					"thumb_gradient_color2" => "rgba(255, 255, 255, .2)",
					    					"show_thumbs_text" => "no",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #BBBBBB",
					    					"show_tooltip" => "yes",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .2,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#000000",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 15,
					    					"name" => "skin_white_preset7",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_white",
					    					"cov_bg_color" => "#FFFFFF",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "frontonesided",
					    					"cov_x_rot" => 3,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 100,
					    					"thumb_x_space_3d" => 30,
					    					"thumb_z_offset_3d" => 150,
					    					"thumb_z_space_3d" => 60,
					    					"thumb_y_angle_3d" => 60,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 50,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#999999",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "yes",
					    					"thumb_gradient_color1" => "rgba(255, 255, 255, 1)",
					    					"thumb_gradient_color2" => "rgba(255, 255, 255, .2)",
					    					"show_thumbs_text" => "no",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #BBBBBB",
					    					"show_tooltip" => "yes",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .2,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#000000",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 16,
					    					"name" => "skin_white_preset8",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_white",
					    					"cov_bg_color" => "#FFFFFF",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "accordion",
					    					"cov_x_rot" => 10,
					    					"cov_y_rot" => 0,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 86,
					    					"thumb_x_space_3d" => 78,
					    					"thumb_z_offset_3d" => 200,
					    					"thumb_z_space_3d" => 93,
					    					"thumb_y_angle_3d" => 70,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 0,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#999999",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "no",
					    					"thumb_gradient_color1" => "rgba(255, 255, 255, 0)",
					    					"thumb_gradient_color2" => "rgba(255, 255, 255, 1)",
					    					"show_thumbs_text" => "no",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #BBBBBB",
					    					"show_tooltip" => "yes",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .2,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#000000",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
					    			array(
					    					// main settings
					    					"id" => 17,
					    					"name" => "skin_white_preset9",
					    					"display_type" => "fluidwidth",
					    					"autoscale" => "yes",
					    					"cov_width" => 940,
					    					"cov_height" => 538,
					    					"skin_path" => $this->_dir_url . "load/skin_white",
					    					"cov_bg_color" => "#FFFFFF",
					    					"cov_bg_image_url" => "",
					    					"bg_repeat" => "repeat-x",
					    					"show_2d_display" => "no",
					    					"cov_start_pos" => "center",
					    					"cov_topology" => "flipping",
					    					"cov_x_rot" => 0,
					    					"cov_y_rot" => 30,
					    					"nr_side_thumbs" => 0,
											"infinite_loop" => "no",
					    					"cov_autoplay" => "no",
					    					"cov_slideshow_delay" => 5000,
					    					"right_click_context_menu" => "developer",
					    					"cov_keyboard_support" => "yes",
											"fluid_width_z_index" => 1000,
					    			
					    					// thumbs settings
					    					"thumb_width" => 400,
					    					"thumb_height" => 266,
					    					"thumb_x_offset_3d" => 86,
					    					"thumb_x_space_3d" => 78,
					    					"thumb_z_offset_3d" => 200,
					    					"thumb_z_space_3d" => 93,
					    					"thumb_y_angle_3d" => 70,
					    					"thumb_x_offset_2d" => 20,
					    					"thumb_x_space_2d" => 30,
					    					"thumb_hover_offset" => 0,
					    					"thumb_border_size" => 0,
					    					"thumb_bg_color" => "#999999",
					    					"thumb_border_color1" => "#FFFFFF",
					    					"thumb_border_color2" => "#FFFFFF",
					    					"transparent_images" => "no",
					    					"thumbs_alignment" => "center",
					    					"max_thumbs_mobile" => 13,
					    					"show_thumbs_gradient" => "no",
					    					"thumb_gradient_color1" => "rgba(255, 255, 255, 0)",
					    					"thumb_gradient_color2" => "rgba(255, 255, 255, 1)",
					    					"show_thumbs_text" => "no",
					    					"text_offset" => 10,
					    					"show_thumb_box_shadow" => "yes",
					    					"box_shadow_css" => "0px 2px 2px #BBBBBB",
					    					"show_tooltip" => "yes",
					    					"dynamic_tooltip" => "yes",
					    					"show_reflection" => "yes",
					    					"reflection_height" => 60,
					    					"reflection_distance" => 0,
					    					"reflection_opacity" => .2,
					    			
					    					// controls settings
					    					"controls_max_width" => 700,
					    					"controls_position" => "bottom",
					    					"controls_offset" => 15,
					    					"show_prev_btn" => "yes",
					    					"show_next_btn" => "yes",
					    					"disable_btns_mobile" => "no",
					    					"show_slideshow_btn" => "yes",
					    					"timer_color" => "#FFFFFF",
					    					"show_scrollbar" => "yes",
					    					"scrollbar_handler_width" => 200,
					    					"scrollbar_text_normal_color" => "#000000",
					    					"scrollbar_text_selected_color" => "#FFFFFF",
					    					"disable_scrollbar_mobile" => "yes",
					    					"enable_mouse_wheel" => "yes",
					    			
					    					// categories menu settings
					    					"show_categories_menu" => "yes",
					    					"start_category" => 1,
					    					"categories_menu_max_width" => 700,
					    					"categories_menu_offset" => 25,
					    					"category_normal_color" => "#999999",
					    					"category_selected_color" => "#000000",
					    			
					    					// lightbox settings
					    					"lightbox_keyboard_support" => "yes",
					    					"show_lightbox_next_prev_btns" => "yes",
					    					"show_lightbox_zoom_btn" => "yes",
					    					"show_lightbox_info_btn" => "yes",
					    					"show_lightbox_slideshow_btn" => "yes",
					    					"show_lightbox_info_default" => "no",
					    					"lightbox_slideshow_autoplay" => "no",
					    					"lightbox_video_autoplay" => "no",
					    					"lightbox_video_width" => 640,
					    					"lightbox_video_height" => 480,
					    					"lightbox_iframe_width" => 800,
					    					"lightbox_iframe_height" => 600,
					    					"lightbox_bg_color" => "#000000",
					    					"lightbox_info_bg_color" => "#FFFFFF",
					    					"lightbox_item_border_color1" => "#FCFDFD",
					    					"lightbox_item_border_color2" => "#E4E4E4",
					    					"lightbox_item_bg_color" => "#333333",
					    					"lightbox_bg_opacity" => .8,
					    					"lightbox_info_bg_opacity" => .9,
					    					"lightbox_border_size" => 0,
					    					"lightbox_border_radius" => 0,
					    					"lightbox_slideshow_delay" => 4000
					    			),
							      );
    }

    public function get_data()
    {
	    $cur_data = get_option("fwds3dcov_data");
	       
	    $this->settings_ar = $cur_data->settings_ar;
	    $this->playlists_ar = $cur_data->playlists_ar;
    }
    
    public function set_data()
    {
    	update_option("fwds3dcov_data", $this);
    }
}

?>